[package]
name = "containix"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["full"] }
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4"] }
which = "6.0.3"
xshell = "0.2.6"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nix = { version = "0.29.0", features = ["fs", "mount", "process", "sched"] }
enum-as-inner = "0.6.0"
